# coding=utf-8

all_city_list = {
    'guangdong': [u'广州', u'深圳', u'佛山', u'惠州', u'珠海', u'揭阳', u'湛江'],
    # 'guangdong': [u'广州', u'深圳', u'佛山', u'huizhou', u'zhuhai', u'jieyang', u'zhanjiang'],
    'jiangsu': [u'南京', u'无锡', u'常州', u'连云港', u'南通', u'扬州', u'盐城'],
    'shanghai': [u'上海'],
    'chongqing': [u'重庆', u'万州'],
    'guizhou': [u'遵义', u'贵阳', u'毕节', u'铜仁', u'安顺'],
    'fujian': [u'福州', u'泉州', u'厦门', u'龙岩'],
    'guangxi': [u'桂林', u'柳州', u'北海', u'南宁', u'梧州', u'百色'],
    'yunnan': [u'西双版纳', u'丽江', u'大理', u'芒市', u'昆明', u'昭通'],
    'zhejiang': [u'杭州', u'宁波', u'温州', u'义乌', u'衢州', u'台州'],
    'jiangxi': [u'南昌', u'赣州', u'宜春', u'景德', u'上饶', u'井冈山'],
    'sichuan': [u'绵阳', u'广元', u'达州', u'南充', u'成都', u'宜宾', u'泸州', u'攀枝花', u'西昌'],
    'hunan': [u'长沙', u'张家界', u'衡阳', u'邵阳'],
    'hubei': [u'武汉', u'宜昌', u'襄阳', u'恩施'],
    'anhui': [u'合肥', u'阜阳', u'安庆', u'池州', u'黄山'],
    'shandong': [u'青岛', u'烟台', u'威海', u'临沂', u'日照', u'东营', u'济南', u'济宁'],
    'heilongjiang': [u'哈尔滨', u'齐齐哈尔', u'牡丹江', u'佳木斯', u'漠河'],
    'liaoning': [u'沈阳', u'朝阳', u'丹东', u'大连'],
    'hainan': [u'三亚', u'海口'],
    'jilin': [u'长春', u'延吉'],
    'xinjiang': [u'阿克苏', u'喀什', u'库尔勒', u'乌鲁木齐', u'伊宁', u'吐鲁番'],
    'neimenggu': [u'包头', u'赤峰', u'海拉尔', u'呼和浩特', u'满洲里', u'乌海', u'乌兰浩特', u'锡林浩特'],
    'shanxi': [u'大同', u'太原', u'运城', u'长治', u'吕梁', u'临汾'],
    'hebei': [u'邯郸'],
    'gansu': [u'敦煌', u'嘉峪关', u'兰州', u'庆阳', u'成县'],
    'shanxi1': [u'汉中', u'西安', u'延安'],
    'xizang': [u'拉萨'],
    'henan': [u'洛阳', u'南阳', u'郑州', u'信阳'],
    'qinghai': [u'西宁'],
    'ningxia': [u'银川', u'中卫'],
}
